@startuml
skinparam classAttributeIconSize 0
skinparam classBorderColor Black
skinparam classBackgroundColor White
skinparam shadowing false
left to right direction
class for  {}
class UserController  {}
class BorrowingAdapter  {}
class EventJoiningAdapter  {}
class TicketGenerator <<interface>> {}
class ICmd <<interface>> {}
class ICommand <<interface>> {}
class Invoker  {}
class AddBookCmd  {}
class AddDonationCmd  {}
class AddUserCmd  {}
class DeleteBookCmd  {}
class DeleteEventCmd  {}
class DeleteUserCmd  {}
class JoinEvent2VolunteerCmd  {}
class LoginByMobilePhoneCmd  {}
class LoginByPasswordCmd  {}
class RetrieveAllBooksCmd  {}
class RetrieveAllUsersCmd  {}
class RetrieveUserCmd  {}
class UpdateUserCmd  {}
class BookManager  {}
class DonationManager  {}
class EventManager  {}
class UserManager  {}
class VolunteringManager  {}
class CharityDonation  {}
class DonationAddon  {}
class GazaDonation  {}
class IDonation <<interface>> {}
class SudanDonation  {}
class SupportUsDonation  {}
class Command <<interface>> {}
class DelayedCommandExecutor  {}
class EmailCommand  {}
class EmailService  {}
class NotificationFacade  {}
class AdminEventFactory  {}
class EventFactory <<interface>> {}
class VolunteerEventFactory  {}
class AvailableBookCollection  {}
class AvailableBookIterator  {}
class BookCollection <<interface>> {}
class BookIterator <<interface>> {}
class BorrowedBookCollection  {}
class BorrowedBookIterator  {}
class EmailPasswordLoginStrategy  {}
class LoginService  {}
class LoginStrategy <<interface>> {}
class MobilePhoneLoginStrategy  {}
class AObserver  {}
class ASubject  {}
class DonationObserver  {}
class DonationSubject  {}
class EventObserver  {}
class EventObserver4Volunteer  {}
class EventSubject  {}
class CreditCardPayment  {}
class FawryPayment  {}
class PaymentMethode  {}
class PaymentStategy <<interface>> {}
class BookProxy  {}
class IBook <<interface>> {}
class public  {}
class DbConnectionSingleton  {}
class AvailableState  {}
class BookContext  {}
class BookState <<interface>> {}
class BookStateFactory  {}
class CheckedOutState  {}
class OverdueState  {}
class RequestedState  {}
class ReservedState  {}
class ReturnedState  {}
class UnavailableState  {}
class addVolunteeringRecordState  {}
class checkAvailabilityState  {}
class EventJoiningState <<interface>> {}
class EventJoiningTemplateContext  {}
class generateTicketState  {}
class handleSeminarEventState  {}
class handleWorkshopEventState  {}
class requestEventState  {}
class requestVolunteeringDetailsState  {}
class SeminarEventJoiningContext  {}
class WorkshopEventJoiningContext  {}
class CreditCardPaymentTemplate  {}
class DonationPaymentTemplate  {}
class FawryPaymentTemplate  {}
class InputValidator  {}
class DonationView  {}
class EventView  {}
class InputHandler  {}
class NotificationView  {}
class UserView  {}
class UtilityHandler  {}
TicketGenerator <|.. BorrowingAdapter
TicketGenerator <|.. EventJoiningAdapter
ICmd <|.. AddBookCmd
ICmd <|.. AddDonationCmd
ICmd <|.. AddUserCmd
ICmd <|.. DeleteBookCmd
ICmd <|.. DeleteEventCmd
ICmd <|.. DeleteUserCmd
ICmd <|.. JoinEvent2VolunteerCmd
ICmd <|.. LoginByMobilePhoneCmd
ICmd <|.. LoginByPasswordCmd
ICmd <|.. RetrieveAllBooksCmd
ICmd <|.. RetrieveAllUsersCmd
ICmd <|.. RetrieveUserCmd
ICmd <|.. UpdateUserCmd
DonationAddon <|-- CharityDonation
IDonation <|.. DonationAddon
DonationAddon <|-- GazaDonation
DonationAddon <|-- SudanDonation
IDonation <|.. SupportUsDonation
Command <|.. EmailCommand
EventFactory <|.. AdminEventFactory
EventFactory <|.. VolunteerEventFactory
BookCollection <|.. AvailableBookCollection
BookIterator <|.. AvailableBookIterator
BookCollection <|.. BorrowedBookCollection
BookIterator <|.. BorrowedBookIterator
LoginStrategy <|.. EmailPasswordLoginStrategy
LoginStrategy <|.. MobilePhoneLoginStrategy
AObserver <|-- DonationObserver
ASubject <|-- DonationSubject
AObserver <|-- EventObserver
AObserver <|-- EventObserver4Volunteer
ASubject <|-- EventSubject
PaymentStategy <|.. CreditCardPayment
PaymentStategy <|.. FawryPayment
IBook <|.. BookProxy
BookState <|.. AvailableState
BookState <|.. CheckedOutState
BookState <|.. OverdueState
BookState <|.. RequestedState
BookState <|.. ReservedState
BookState <|.. ReturnedState
BookState <|.. UnavailableState
EventJoiningState <|.. addVolunteeringRecordState
EventJoiningState <|.. checkAvailabilityState
EventJoiningState <|.. generateTicketState
EventJoiningState <|.. handleSeminarEventState
EventJoiningState <|.. handleWorkshopEventState
EventJoiningState <|.. requestEventState
EventJoiningState <|.. requestVolunteeringDetailsState
EventJoiningTemplateContext <|-- SeminarEventJoiningContext
EventJoiningTemplateContext <|-- WorkshopEventJoiningContext
DonationPaymentTemplate <|-- CreditCardPaymentTemplate
DonationPaymentTemplate <|-- FawryPaymentTemplate
for --> IDonation
UserController --> UserView
UserController --> UtilityHandler
UserController --> InputHandler
UserController --> NotificationView
UserController --> EventView
UserController --> DonationView
UserController --> Invoker
UserController --> UserManager
UserController --> IDonation
UserController --> DonationManager
UserController --> DonationPaymentTemplate
UserController --> NotificationFacade
UserController --> PaymentStategy
UserController --> PaymentMethode
UserController --> EventFactory
UserController --> EventManager
UserController --> VolunteringManager
UserController --> TicketGenerator
UserController --> EventJoiningTemplateContext
UserController --> EventJoiningTemplateContext
UserController --> BookManager
UserController --> BookManager
UserController --> BookManager
UserController --> BookIterator
UserController --> IBook
UserController --> BorrowedBookCollection
UserController --> BookContext
UserController --> UserManager
UserController --> UserManager
BorrowingAdapter --> BorrowedBookCollection
BorrowingAdapter --> UtilityHandler
BorrowingAdapter --> BookIterator
TicketGenerator --> TicketGenerator
AddBookCmd --> BookManager
AddDonationCmd --> DonationManager
AddUserCmd --> UserManager
DeleteBookCmd --> BookManager
DeleteEventCmd --> EventManager
DeleteUserCmd --> UserManager
JoinEvent2VolunteerCmd --> VolunteringManager
LoginByMobilePhoneCmd --> UserManager
LoginByPasswordCmd --> UserManager
RetrieveAllBooksCmd --> BookManager
RetrieveAllUsersCmd --> UserManager
RetrieveUserCmd --> UserManager
UpdateUserCmd --> UserManager
UserManager --> LoginService
UserManager --> LoginService
DonationAddon --> IDonation
EmailCommand --> NotificationFacade
EmailCommand --> DelayedCommandExecutor
EmailService --> UtilityHandler
NotificationFacade --> EmailService
NotificationFacade --> UtilityHandler
AdminEventFactory --> UtilityHandler
VolunteerEventFactory --> UtilityHandler
LoginService --> LoginStrategy
AObserver --> ASubject
DonationObserver --> DonationSubject
DonationSubject --> NotificationFacade
DonationSubject --> EmailCommand
EventObserver --> EventSubject
EventObserver4Volunteer --> EventSubject
CreditCardPayment --> UtilityHandler
FawryPayment --> UtilityHandler
PaymentMethode --> PaymentStategy
DbConnectionSingleton --> DbConnectionSingleton
AvailableState --> BookIterator
BookContext --> BookState
BookContext --> BorrowedBookCollection
BookContext --> UtilityHandler
BookContext --> BookIterator
CheckedOutState --> BookIterator
CheckedOutState --> BookIterator
OverdueState --> BookIterator
OverdueState --> BookIterator
RequestedState --> BookIterator
RequestedState --> BookIterator
ReservedState --> BookIterator
ReservedState --> BorrowingAdapter
ReservedState --> BookIterator
ReturnedState --> BookIterator
ReturnedState --> BookIterator
UnavailableState --> BookIterator
UnavailableState --> BookIterator
addVolunteeringRecordState --> Invoker
EventJoiningTemplateContext --> UtilityHandler
EventJoiningTemplateContext --> InputHandler
EventJoiningTemplateContext --> VolunteringManager
EventJoiningTemplateContext --> EventJoiningState
generateTicketState --> TicketGenerator
CreditCardPaymentTemplate --> PaymentMethode
DonationPaymentTemplate --> UtilityHandler
FawryPaymentTemplate --> PaymentMethode
EventView --> UtilityHandler
InputHandler --> UtilityHandler
UserView --> UserController
@enduml